version: "3.4"

x-app: &app_base
  depends_on:
    - db
    - redis
  image: ${IMAGE_NAME}
  env_file:
    .env.test
  build:
    context: .
    args:
      - BUNDLER_VERSION=2.2.28
  links:
    - db
  volumes:
    - ruby-bundle:/usr/local/bundle

