version: "3.4"

x-app: &app_base
  depends_on:
    - db
    - redis
  image: ${IMAGE_NAME}
  env_file:
    .env
  build:
    context: .
    args:
      - BUNDLER_VERSION=2.2.28
  links:
    - db
  volumes:
    - ruby-bundle:/usr/local/bundle

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6.0-rc3-alpine
    sysctls:
      - net.core.somaxconn=511
  app:
    <<: *app_base
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: bin/docker-entrypoint
  sidekiq:
    <<: *app_base
    depends_on:
      - app
    command: sh -c './bin/wait-for app:3000 -- bundle exec sidekiq'

volumes:
  ruby-bundle:
  db-data:
