version: "3.4"

x-app: &app_base
  depends_on:
    - db
    - redis
  image: ${IMAGE_NAME}
  env_file:
    .env
  build:
    image: ghcr.io/annaaleynik/thanku-api:main
    args:
      - BUNDLER_VERSION=2.2.28
  links:
    - db
  volumes:
    - ruby-bundle:/usr/local/bundle
