server:
  http_listen_port: 3100
  grpc_listen_port: 9096

positions:
  filename: /tmp/positions.yaml

client:
  url: https://181579:eyJrIjoiMzBkNmUxMjlhMzM2ZWE2NjZhZDAxNjA5MjA2ZTQ4ZTJjMGM4MWI4NiIsIm4iOiJUcmVsbG9OIiwiaWQiOjYxNzYwMH0=@logs-prod3.grafana.net/api/prom/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /log/*.log