name: Deploy

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Build and push
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --remove-orphans
