name: Test Quality
on:
  push:
jobs:
  test:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - "5432:5432"
        env:
          ImageOS: ubuntu18
          POSTGRES_DB: thanku-api_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/thanku-api_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true
          ruby-version: '2.7.5'
      - name: Install yarn dependencies
        run: yarn install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rspec
      
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true
          ruby-version: '2.7.5'
      - name: Lint
        run: bin/quality
